#:schema https://yazi-rs.github.io/schemas/theme.json

[mgr]

# tmTheme files can be found here: https://github.com/scottmckendry/cyberdream.nvim/tree/main/extras/textmate 
syntect_theme = "../bat/themes/cyberdream.tmTheme"

border_style = { fg = "#3c4048" }
cwd = { fg = "#5ef1ff" }
find_keyword = { bold = true, fg = "#5eff6c" }
find_position = { fg = "#ffffff" }
marker_copied = { bg = "#f1ff5e", fg = "#f1ff5e" }
marker_cut = { bg = "#ff6e5e", fg = "#ff6e5e" }
marker_selected = { bg = "#3c4048", fg = "#5eff6c" }
count_selected = { bg = "#5eff6c", fg = "#16181a" }
count_copied = { bg = "#f1ff5e", fg = "#16181a" }
count_cut = { bg = "#ff6e5e", fg = "#16181a" }

[cmp]
active = { bg = "#7b8496", fg = "#bd5eff" }
border = { fg = "#5ea1ff" }
inactive = { fg = "#ffffff" }

[tabs]
active = { bg = "#5ea1ff", fg = "#16181a" }
inactive = { bg = "#3c4048", fg = "#ffffff" }

[filetype]
rules = [
    { fg = "#5ef1ff", mime = "image/*" },
    { fg = "#f1ff5e", mime = "video/*" },
    { fg = "#f1ff5e", mime = "audio/*" },
    { fg = "#bd5eff", mime = "application/zip" },
    { fg = "#bd5eff", mime = "application/gzip" },
    { fg = "#bd5eff", mime = "application/x-tar" },
    { fg = "#bd5eff", mime = "application/x-bzip" },
    { fg = "#bd5eff", mime = "application/x-bzip2" },
    { fg = "#bd5eff", mime = "application/x-7z-compressed" },
    { fg = "#bd5eff", mime = "application/x-rar" },
    { fg = "#bd5eff", mime = "application/xz" },
    { fg = "#5eff6c", mime = "application/doc" },
    { fg = "#5eff6c", mime = "application/pdf" },
    { fg = "#5eff6c", mime = "application/rtf" },
    { fg = "#5eff6c", mime = "application/vnd.*" },
    { bold = true, fg = "#5ea1ff", mime = "inode/directory" },
    { fg = "#ffffff", mime = "*" }
]

[help]
desc = { fg = "#ffffff" }
footer = { fg = "#ffffff" }
hovered = { bg = "#7b8496", fg = "#ffffff" }
on = { fg = "#bd5eff" }
run = { fg = "#5ef1ff" }

[input]
border = { fg = "#5ea1ff" }
selected = { bg = "#7b8496" }
title = { fg = "#ffffff" }
value = { fg = "#ffffff" }

[pick]
active = { fg = "#bd5eff" }
border = { fg = "#5ea1ff" }
inactive = { fg = "#ffffff" }

[mode]
normal_main = { bg = "#5ea1ff", bold = true, fg = "#16181a" }
select_main = { bg = "#5eff6c", bold = true, fg = "#16181a" }
unset_main = { bg = "#ff5ef1", bold = true, fg = "#16181a" }

[status]
perm_sep = { fg = "#5ef1ff" }
perm_type = { fg = "#5ea1ff" }
perm_read = { fg = "#f1ff5e" }
perm_write = { fg = "#ff6e5e" }
perm_exec = { fg = "#5eff6c" }
progress_error = { bg = "#16181a", fg = "#ff6e5e" }
progress_label = { bg = "#16181a", fg = "#ffffff" }
progress_normal = { bg = "#16181a", fg = "#ffffff" }

[tasks]
border = { fg = "#5ea1ff" }
hovered = { bg = "#7b8496", fg = "#ffffff" }
title = { fg = "#ffffff" }

[which]
cand = { fg = "#5ef1ff" }
desc = { fg = "#ffffff" }
mask = { bg = "#3c4048" }
rest = { fg = "#ff5ef1" }
separator_style = { fg = "#7b8496" }
