[manager] 
    # tmTheme files can be found here: https://github.com/scottmckendry/cyberdream.nvim/tree/main/extras/textmate 
    syntect_theme = "../bat/themes/cyberdream.tmTheme"
    [manager.border_style]
        fg = "#7b8496"

    [manager.cwd]
        fg = "#5ef1ff"

    [manager.find_keyword]
        bold = true
        fg = "#5eff6c"

    [manager.find_position]
        fg = "#ffffff"

    [manager.hovered]
        bg = "#7b8496"
        bold = true
        fg = "#ffffff"

    [manager.marker_copied]
        bg = "#f1ff5e"
        fg = "#f1ff5e"

    [manager.marker_cut]
        bg = "#ff6e5e"
        fg = "#ff6e5e"

    [manager.marker_selected]
        bg = "#5eff6c"
        fg = "#5eff6c"

    [manager.preview_hovered]
        bg = "#7b8496"
        bold = true
        fg = "#ffffff"

    [manager.tab_active]
        bg = "#5ea1ff"
        fg = "#16181a"

    [manager.tab_inactive]
        bg = "#3c4048"
        fg = "#ffffff"

[completion]
    [completion.active]
        bg = "#7b8496"
        fg = "#bd5eff"

    [completion.border]
        fg = "#5ea1ff"

    [completion.inactive]
        fg = "#ffffff"

[[filetype.rules]]
    fg = "#5ef1ff"
    mime = "image/*"

[[filetype.rules]]
    fg = "#f1ff5e"
    mime = "video/*"

[[filetype.rules]]
    fg = "#f1ff5e"
    mime = "audio/*"

[[filetype.rules]]
    fg = "#bd5eff"
    mime = "application/zip"

[[filetype.rules]]
    fg = "#bd5eff"
    mime = "application/gzip"

[[filetype.rules]]
    fg = "#bd5eff"
    mime = "application/x-tar"

[[filetype.rules]]
    fg = "#bd5eff"
    mime = "application/x-bzip"

[[filetype.rules]]
    fg = "#bd5eff"
    mime = "application/x-bzip2"

[[filetype.rules]]
    fg = "#bd5eff"
    mime = "application/x-7z-compressed"

[[filetype.rules]]
    fg = "#bd5eff"
    mime = "application/x-rar"

[[filetype.rules]]
    fg = "#bd5eff"
    mime = "application/xz"

[[filetype.rules]]
    fg = "#5eff6c"
    mime = "application/doc"

[[filetype.rules]]
    fg = "#5eff6c"
    mime = "application/pdf"

[[filetype.rules]]
    fg = "#5eff6c"
    mime = "application/rtf"

[[filetype.rules]]
    fg = "#5eff6c"
    mime = "application/vnd.*"

[[filetype.rules]]
    bold = true
    fg = "#5ea1ff"
    mime = "inode/directory"

[[filetype.rules]]
    fg = "#ffffff"
    mime = "*"

[help]
    [help.desc]
        fg = "#ffffff"

    [help.footer]
        fg = "#ffffff"

    [help.hovered]
        bg = "#7b8496"
        fg = "#ffffff"

    [help.on]
        fg = "#bd5eff"

    [help.run]
        fg = "#5ef1ff"

[input]
    [input.border]
        fg = "#5ea1ff"

    [input.selected]
        bg = "#7b8496"

    [input.title]
        fg = "#ffffff"

    [input.value]
        fg = "#ffffff"

[select]
    [select.active]
        fg = "#bd5eff"

    [select.border]
        fg = "#5ea1ff"

    [select.inactive]
        fg = "#ffffff"

[status]
    [status.mode_normal]
        bg = "#5ea1ff"
        bold = true
        fg = "#16181a"

    [status.mode_select]
        bg = "#5eff6c"
        bold = true
        fg = "#16181a"

    [status.mode_unset]
        bg = "#ff5ef1"
        bold = true
        fg = "#16181a"

    [status.permissions_r]
        fg = "#f1ff5e"

    [status.permissions_s]
        fg = "#5ef1ff"

    [status.permissions_t]
        fg = "#5ea1ff"

    [status.permissions_w]
        fg = "#ff6e5e"

    [status.permissions_x]
        fg = "#5eff6c"

    [status.progress_error]
        bg = "#16181a"
        fg = "#ff6e5e"

    [status.progress_label]
        bg = "#16181a"
        fg = "#ffffff"

    [status.progress_normal]
        bg = "#16181a"
        fg = "#ffffff"

    [status.separator_style]
        bg = "#3c4048"
        fg = "#3c4048"

[tasks]
    [tasks.border]
        fg = "#5ea1ff"

    [tasks.hovered]
        bg = "#7b8496"
        fg = "#ffffff"

    [tasks.title]
        fg = "#ffffff"

[which]
    [which.cand]
        fg = "#5ef1ff"

    [which.desc]
        fg = "#ffffff"

    [which.mask]
        bg = "#3c4048"

    [which.rest]
        fg = "#ff5ef1"

    [which.separator_style]
        fg = "#7b8496"
