#:schema https://yazi-rs.github.io/schemas/theme.json

[mgr]

# tmTheme files can be found here: https://github.com/scottmckendry/cyberdream.nvim/tree/main/extras/textmate 
syntect_theme = "../bat/themes/cyberdream.tmTheme"

border_style = { fg = "#acacac" }
cwd = { fg = "#008c99" }
find_keyword = { bold = true, fg = "#008b0c" }
find_position = { fg = "#16181a" }
marker_copied = { bg = "#997b00", fg = "#997b00" }
marker_cut = { bg = "#d11500", fg = "#d11500" }
marker_selected = { bg = "#acacac", fg = "#008b0c" }
count_selected = { bg = "#008b0c", fg = "#ffffff" }
count_copied = { bg = "#997b00", fg = "#ffffff" }
count_cut = { bg = "#d11500", fg = "#ffffff" }

[cmp]
active = { bg = "#7b8496", fg = "#a018ff" }
border = { fg = "#0057d1" }
inactive = { fg = "#16181a" }

[tabs]
active = { bg = "#0057d1", fg = "#ffffff" }
inactive = { bg = "#acacac", fg = "#16181a" }

[filetype]
rules = [
    { fg = "#008c99", mime = "image/*" },
    { fg = "#997b00", mime = "video/*" },
    { fg = "#997b00", mime = "audio/*" },
    { fg = "#a018ff", mime = "application/zip" },
    { fg = "#a018ff", mime = "application/gzip" },
    { fg = "#a018ff", mime = "application/x-tar" },
    { fg = "#a018ff", mime = "application/x-bzip" },
    { fg = "#a018ff", mime = "application/x-bzip2" },
    { fg = "#a018ff", mime = "application/x-7z-compressed" },
    { fg = "#a018ff", mime = "application/x-rar" },
    { fg = "#a018ff", mime = "application/xz" },
    { fg = "#008b0c", mime = "application/doc" },
    { fg = "#008b0c", mime = "application/pdf" },
    { fg = "#008b0c", mime = "application/rtf" },
    { fg = "#008b0c", mime = "application/vnd.*" },
    { bold = true, fg = "#0057d1", mime = "inode/directory" },
    { fg = "#16181a", mime = "*" }
]

[help]
desc = { fg = "#16181a" }
footer = { fg = "#16181a" }
hovered = { bg = "#7b8496", fg = "#16181a" }
on = { fg = "#a018ff" }
run = { fg = "#008c99" }

[input]
border = { fg = "#0057d1" }
selected = { bg = "#7b8496" }
title = { fg = "#16181a" }
value = { fg = "#16181a" }

[pick]
active = { fg = "#a018ff" }
border = { fg = "#0057d1" }
inactive = { fg = "#16181a" }

[mode]
normal_main = { bg = "#0057d1", bold = true, fg = "#ffffff" }
select_main = { bg = "#008b0c", bold = true, fg = "#ffffff" }
unset_main = { bg = "#d100bf", bold = true, fg = "#ffffff" }

[status]
perm_sep = { fg = "#008c99" }
perm_type = { fg = "#0057d1" }
perm_read = { fg = "#997b00" }
perm_write = { fg = "#d11500" }
perm_exec = { fg = "#008b0c" }
progress_error = { bg = "#ffffff", fg = "#d11500" }
progress_label = { bg = "#ffffff", fg = "#16181a" }
progress_normal = { bg = "#ffffff", fg = "#16181a" }

[tasks]
border = { fg = "#0057d1" }
hovered = { bg = "#7b8496", fg = "#16181a" }
title = { fg = "#16181a" }

[which]
cand = { fg = "#008c99" }
desc = { fg = "#16181a" }
mask = { bg = "#acacac" }
rest = { fg = "#d100bf" }
separator_style = { fg = "#7b8496" }
